LIB_SYSTEM/LIB_SYSTEM/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('polls/',include('polls.urls')),
    path('admin/', admin.site.urls),
]

LIB_SYSTEM/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/result/', views.voted, name='voted'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

LIB_SYSTEM/polls/models.py
from django.db import models

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

LIB_SYSTEM/polls/views.py
from django.http import HttpResponse
from .models import Question, Choice
from django.template import loader
from django.http import Http404
from django.shortcuts import get_object_or_404, render

# Create your views here.
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)
    
def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

def voted(request, question_id):
	if request.method=='POST':
		qstobj=Question.objects.get(pk=question_id)
		try:
			choiceobj=get_object_or_404(Choice,pk=request.POST['vote'])
		except:
			return HttpResponse("Please select an option")
		else:
			choiceobj.votes+=1
			choiceobj.save()
			return render(request,'polls/detail.html',{'question':qstobj})
	return render(request,'polls/detail.html')

def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)

LIB_SYSTEM/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>
<ul>
<form method="post" action="{%url 'polls:voted' question.id%}">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="vote" value="{{choice.id}}" id="question{{forloop.counter}}}" >{{ choice.choice_text }}</input>---{{choice.votes}}
{% endfor %}
<input type="submit" value="Vote" />
</form>
</ul>

LIB_SYSTEM/polls/templates/polls/index.html
{% if latest_question_list %}
<ul>
    {% for question in latest_question_list %}
      <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text}}
</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

LIB_SYSTEM/polls/templates/polls/results.html
{% extends 'polls/base.html' %}

{% block polls_content %}
<h1>{{ poll.question }}</h1>

<ul>
{% for choice in poll.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' poll.id %}">Vote again?</a>
{% endblock %}